ARG UBUNTU_VERSION=20.04
ARG CUDA_VERSION=11.6.1
ARG BASE_IMAGE=nvidia/cuda:${CUDA_VERSION}-base-ubuntu${UBUNTU_VERSION}

FROM ${BASE_IMAGE} as base

ENV TORCH_VERSION=1.13.0
ENV CUDA_VERSION_SHORT=cu116
ENV PYTHON_VERSION=3.8
ENV GO_VERSION=1.20.2

SHELL ["/bin/bash", "-c"]

ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y --no-install-recommends \
        build-essential ca-certificates ccache cmake curl git libjpeg-dev libgl1-mesa-glx \
        libegl1-mesa libxrandr2 libxrandr2 libxss1 libxcursor1 libxcomposite1 libasound2 \
        libxi6 libxtst6 wget libpng-dev p7zip-rar neovim tmux \
        libglib2.0-0 libsm6 libxrender1 libxext6 unzip \
        sudo \
        libappindicator3-1 && \
    rm -rf /var/lib/apt/lists/*
RUN /usr/sbin/update-ccache-symlinks

#install arduino-cli
RUN wget -qO arduino-cli.tar.gz https://downloads.arduino.cc/arduino-cli/arduino-cli_latest_Linux_64bit.tar.gz
RUN tar xf arduino-cli.tar.gz -C /usr/local/bin arduino-cli
RUN rm arduino-cli.tar.gz
RUN arduino-cli config init
RUN arduino-cli config set library.enable_unsafe_install true

COPY ./embedded/firmata/setup.sh /root/setup.sh
RUN chmod +x /root/setup.sh && /root/setup.sh

RUN apt-get update && apt-get install -y python${PYTHON_VERSION} python3-pip
RUN ln -sf /usr/bin/python3.8 /usr/local/bin/python
RUN alias pip=pip3

#copy in requirements.txt from robot folder
COPY ./robot/requirements.txt ./requirements.txt
RUN pip install -r ./requirements.txt
RUN pip install torch==${TORCH_VERSION}+${CUDA_VERSION_SHORT} torchvision --extra-index-url https://download.pytorch.org/whl/${CUDA_VERSION_SHORT}

RUN echo "alias v=nvim" >> /root/.bashrc
RUN echo "set +e" >> /root/.bashrc
RUN echo "export PYTHONPATH=$PYTHONPATH:/nexus" >> /root/.bachrc

#when running with utils/docker/run_container.sh, this gets linked with the root nexus directory
RUN mkdir nexus
WORKDIR nexus
