#!/bin/bash
set -o errexit

# Author: David Underhill
# Script to permanently delete files/folders from your git repository.  To use 
# it, cd to your repository's root and then run the script with a list of paths
# you want to delete, e.g., git-delete-history path1 path2

echo "going"

if [ $# -eq 0 ]; then
    exit 0
fi

# make sure we're at the root of git repo
if [ ! -d .git ]; then
    echo "Error: must run this script from the root of a git repository"
    exit 1
fi

# remove all paths passed as arguments from the history of the repo
files=segmentation/trained_model.pth segmentation/trained_model5.pth segmentation/trained_model2.pth segmentation/trained_model3.pth segmentation/trained_model4.pth classification/trained_model_1642301583.1151104.pth classification/trained_model_1642323295.3624196.pth classification/trained_model_1642303473.6658857.pth classification/trained_model_1642377156.0191455.pth classification/trained_model_1642323398.039468.pth classification/trained_model_1642308618.1758704.pth classification/trained_model_1642323753.123895.pth
git filter-branch --index-filter "git rm -rf --cached --ignore-unmatch $files" HEAD

# remove the temporary history git-filter-branch otherwise leaves behind for a long time
rm -rf .git/refs/original/ && git reflog expire --all &&  git gc --aggressive --prune

echo "done"
