/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/pause': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Pause System */
    put: operations['pause_system_pause_put'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/resume': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Resume System */
    put: operations['resume_system_resume_put'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/irl-runtime-params': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Irl Runtime Params */
    get: operations['get_irl_runtime_params_irl_runtime_params_get'];
    /** Update Irl Runtime Params */
    put: operations['update_irl_runtime_params_irl_runtime_params_put'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][];
    };
    /** IRLSystemRuntimeParams */
    IRLSystemRuntimeParams: {
      /** Mainconveyorspeed */
      mainConveyorSpeed: number;
      /** Feederconveyorspeed */
      feederConveyorSpeed: number;
      /** Firstvibrationhoppermotorspeed */
      firstVibrationHopperMotorSpeed: number;
      /** Secondvibrationhoppermotorspeed */
      secondVibrationHopperMotorSpeed: number;
      /** Firstvibrationhoppermotorpulsems */
      firstVibrationHopperMotorPulseMs: number;
      /** Secondvibrationhoppermotorpulsems */
      secondVibrationHopperMotorPulseMs: number;
      /** Feederconveyorpulsems */
      feederConveyorPulseMs: number;
      /** Firstvibrationhoppermotorpausems */
      firstVibrationHopperMotorPauseMs: number;
      /** Secondvibrationhoppermotorpausems */
      secondVibrationHopperMotorPauseMs: number;
      /** Feederconveyorpausems */
      feederConveyorPauseMs: number;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  pause_system_pause_put: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  resume_system_resume_put: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  get_irl_runtime_params_irl_runtime_params_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['IRLSystemRuntimeParams'];
        };
      };
    };
  };
  update_irl_runtime_params_irl_runtime_params_put: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['IRLSystemRuntimeParams'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
}
